### ISSUE TITLE
cte fails when specifying dropped amplicons

### ISSUE THREAD

**Issue by Danderson123** [iqbal-lab-org/covid-truth-eval#2]
Hey Martin,

I have added dropped amplicon information to the truth vcfs I am using to evaluate viridian assemblies but keep getting the error below. Is there a bug or am I doing something wrong?

`[2022-04-08T11:30:13 cte INFO] Load runs from file cte_viridian_output/ART_assemblies/manifest.tsv
[2022-04-08T11:30:13 cte INFO] ============================================================
[2022-04-08T11:30:13 cte INFO] Start processing run 1/10: 0_a
[2022-04-08T11:30:13 cte INFO] Start evaluating viridian_assemblies/ART_assemblies/0_a/consensus.fa
[2022-04-08T11:30:13 cte INFO] Using reference FASTA: /usr/local/lib/python3.8/dist-packages/cte/data/MN908947.fasta
[2022-04-08T11:30:13 cte INFO] Using truth VCF: truth_vcfs/0_a/04.truth_dropped.vcf
[2022-04-08T11:30:13 cte INFO] Loading primers from file /usr/local/lib/python3.8/dist-packages/cte/data/covid-artic-v4.vwf.tsv
[2022-04-08T11:30:13 cte INFO] Making multiple sequence alignment (ref vs truth vs seq to evaluate)
[2022-04-08T11:30:13 cte INFO] Run command: mafft --anysymbol --nuc --quiet --maxiterate 1000 --thread 1 cte_viridian_output/ART_assemblies/OUT/Processing/0_a/MSA/to_align.fa > cte_viridian_output/ART_assemblies/OUT/Processing/0_a/MSA/msa.fasta
[2022-04-08T11:30:17 cte INFO] Return code = 0 from: mafft --anysymbol --nuc --quiet --maxiterate 1000 --thread 1 cte_viridian_output/ART_assemblies/OUT/Processing/0_a/MSA/to_align.fa > cte_viridian_output/ART_assemblies/OUT/Processing/0_a/MSA/msa.fasta
[2022-04-08T11:30:17 cte INFO] Gathering stats from MSA
Traceback (most recent call last):
  File "/usr/local/bin/cte", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cte/__main__.py", line 98, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/cte/tasks/eval_runs.py", line 13, in run
    multi_run_evaluator.evaluate_runs(
  File "/usr/local/lib/python3.8/dist-packages/cte/multi_run_evaluator.py", line 48, in evaluate_runs
    new_results = one_run_evaluator.eval_one_fasta(
  File "/usr/local/lib/python3.8/dist-packages/cte/one_run_evaluator.py", line 44, in eval_one_fasta
    multi_aln.gather_stats(amp_scheme, per_pos_tsv=per_position_tsv_out)
  File "/usr/local/lib/python3.8/dist-packages/cte/msa.py", line 335, in gather_stats
    self.stats = stats_from_three_way_aln(
  File "/usr/local/lib/python3.8/dist-packages/cte/msa.py", line 223, in stats_from_three_way_aln
    row, col = aln_bases_to_stats_row_and_col(ref_base, truth_base, eval_base)
  File "/usr/local/lib/python3.8/dist-packages/cte/msa.py", line 199, in aln_bases_to_stats_row_and_col
    raise NotImplementedError(
NotImplementedError: Case not found for ref,truth,cons bases: A,Z,G`

Have attached the failed vcf.

Thanks!
Daniel
[04.truth_dropped.vcf.gz](https://github.com/iqbal-lab-org/covid-truth-eval/files/8452821/04.truth_dropped.vcf.gz)

**Comment by martinghunt** [comment]
Thanks for finding! Is a bug. I've fixed it (commit 7e9b66c5053140d6725e8198bbde7972856605a1).

That will now get reported as truth `Dropped_amplicon`, consensus `Called_other`.
